apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: poc-k8s-pods-commu--app1:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: APP2_URL
          value: http://app2-service/receive
        ports:
        - containerPort: 8000

